name: Dental Hub CI/CD
on: [push, pull_request]

jobs:
  quality-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
          
      - name: Run Security Audit
        run: npm audit --production
          
      - name: Build Project
        run: npm run build